### ISSUE TITLE
Compiling jm.bcs throws syntax error

### ISSUE THREAD

**Issue by Iarex** [wormt/bcc#11]
Compiling with GZDB directly, throws a missing zcommon.h which it could be solved by deleting **#include "zcommon.h"** because **zcommon.bcs** does its job.

In some function declarations have a "msgbuild" keyword which generates a syntax error when we compile with GZDB and appears to be not declared too. Deleting that keyword from its corresponding functions solves the syntax error problem. However, the HudMessage depends of that keyword to generate a message to print.

For now, I'm icluding the **zcommon.bcs** and **jm.bcs** in their corresponding order.

**Comment by positively-charged** [comment]
I have fixed the JM library, and also some other example files. I don't recommend using this JM library. It's meant to be an example file and is outdated. The [latest JM library](https://github.com/Hypnotoad90/jumpmaze-zan/tree/master/jm_core/pk3/scripts) can be found in the JM repository.

I'm still working on the GZDB configuration files for BCC. I've included them below. They are not finished yet, but are usable. Just replace the files in the GZDB folder with the files from a configuration ZIP file found below.

GZDB configuration files (work-in-progress):
[bcc_0.8.0.12_32bit_gzdb.zip](https://github.com/wormt/bcc/files/1272616/bcc_0.8.0.12_32bit_gzdb.zip)
[bcc_0.8.0.12_64bit_gzdb.zip](https://github.com/wormt/bcc/files/1272618/bcc_0.8.0.12_64bit_gzdb.zip)
