### ISSUE TITLE
[ACC Compatibility] "For" operator

### ISSUE THREAD

**Issue by Monsterovich** [wormt/bcc#3]
For example, my acs code:

for (int i = 0; i < 10; i++)
{
...
}

for (i = a; i < 10; i++) // << error here
{
...
}

bcc says that variable 'i' is not declared. I have no such error with acc.

**Comment by positively-charged** [comment]
I fixed this in the upcoming version of bcc, so your old ACS code should now work.

In scripts and functions outside a namespace block, variables have function scope. If you want the variables to have block scope, like in an older version of bcc, use the `let` keyword:

```
script 1 open {
   for ( let int i = 0; i < 10; i++ ) {
      Print( d: i );
   }
   for ( let int i = 0; i < 10; i++ ) {
      Print( d: i );
   }
}
```

In a namespace block, the `let` keyword is implied, so you get block scoping by default. The `let` keyword is not necessary:

```
namespace upmost {
   script 1 open {
      for ( int i = 0; i < 10; i++ ) {
         Print( d: i );
      }
      for ( int i = 0; i < 10; i++ ) {
         Print( d: i );
      }
   }
}
```
