### ISSUE TITLE
Named Clientside Script doesn't have proper ConsolePlayer() value

### ISSUE THREAD

**Issue by Doruk-Aksoy** [wormt/bcc#9]
More details on this ticket: http://zandronum.com/tracker/view.php?id=3153

**Comment by positively-charged** [comment]
Sorry it took a while to respond. Got burned out working on this project. Did not wanna be near it. This should be fixed in the latest release: [0.8.0](https://github.com/wormt/bcc/releases/tag/0.8.0)
